### ISSUE TITLE
The specified child already has a parent. You must call removeView() 

### ISSUE THREAD

**Issue by Fahad-pnw** [ncapdevi/FragNav#103]
i was making some modifications when android forced update to API 26 as there were a few bugs that weren't resolving.

now app was just working fine with frag-nav 1.4.0 however, since i updated the support tools, bottom nav crashes. I understand the issue is that the parent isn't popping and the fragment i'm trying to access already has a parent, is there a quicker way than to integrate the newer version? i've been looking at revisions, i tried various methods and i'm just failing at it so far, been trying for a few hours.

java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

  at com.pnw.xyz.MainActivity.switchTab(MainActivity.java:428)
                      at com.pnw.xyz.MainActivity$1.onClick(MainActivity.java:112)

**Comment by ncapdevi** [comment]
Could you give a bit more info about how this situation is occurring? Ideally some code that would allow me to reproduce it within the sample app?

**Comment by dakshays** [comment]
I'm also getting the same exception in Navigation Drawer Stack,
It was working good on API 26 before. After updating compile sdk version to 27 something goes wrong. 

From Navigation Drawer Stack, Add a Recent Tab and do Back press it is throwing Exception.
 
**Exception**
`java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
                                                                         at android.view.ViewGroup.addViewInner(ViewGroup.java:4417)
                                                                         at android.view.ViewGroup.addView(ViewGroup.java:4258)
                                                                         at android.view.ViewGroup.addView(ViewGroup.java:4198)
                                                                         at android.view.ViewGroup.addView(ViewGroup.java:4171)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1425)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
                                                                         at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:792)
                                                                         at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
                                                                         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
                                                                         at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
                                                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
                                                                         at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6236)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)`

**Comment by codewrangler1** [comment]
Anybody have a solution to this? I am having the same issue...thanks!

**Comment by Fahad-pnw** [comment]
i resolved it by spending a few hours comparing the process / newer docs, don't even remember what i did that fixed it. i'm going share some code here if it helps.

` ImagePipelineConfig config = ImagePipelineConfig.newBuilder(this)
                .setProgressiveJpegConfig(new SimpleProgressiveJpegConfig())
                .setResizeAndRotateEnabledForNetwork(true)
                .setDownsampleEnabled(true)
                .build();
        setContentView(R.layout.activity_home);


        fragments.add(new HomeFragment());
        fragments.add(new SearchFragment());
        fragments.add(new PlaylistsFragment());
        fragments.add(new SettingsFragment());

        //mNavController = new FragNavController(savedInstanceState, getSupportFragmentManager(), R.id.fragments_container, fragments, INDEX_HOME);

        setContentView(R.layout.activity_home);

        mNavController = FragNavController.newBuilder(savedInstanceState, getSupportFragmentManager(), R.id.fragments_container)
                .rootFragments(fragments)
                .transactionListener(this)
                .defaultTransactionOptions(FragNavTransactionOptions.newBuilder().build())
                .build();
`

**Comment by Fahad-pnw** [comment]
if i remember it right, this part solely fixed it for me.

`        //mNavController = new FragNavController(savedInstanceState, getSupportFragmentManager(), R.id.fragments_container, fragments, INDEX_HOME);

        setContentView(R.layout.activity_home);

        mNavController = FragNavController.newBuilder(savedInstanceState, getSupportFragmentManager(), R.id.fragments_container)
                .rootFragments(fragments)
                .transactionListener(this)
                .defaultTransactionOptions(FragNavTransactionOptions.newBuilder().build())
                .build();
`

**Comment by tehcpu** [comment]
Hi, @Fahad-pnw.
Did you use the [BottomBar](https://github.com/roughike/BottomBar) library? I do not see it has been attached to the controller's initialization in your code snippet. Also, unfortunately it didn't do the trick for me, still having an error:
`The specified child already has a parent. You must call removeView() on the child's parent first.`
The only fix i know for now - downgrade android support to 26.0.2 version (with all dependencies, of course).

**Comment by codewrangler1** [comment]
FYI...I am using API 26.0.2 and in my case, the crash was happening because of custom animations set for my fragments. Commenting out the call to set the custom animation, fixed the issue.

Still investigating what it is about the animations that causes the crash.

**Comment by jaideepreddy** [comment]
Hi @codewrangler1,
After updating to API 27.0.2 from 26.0.1, I am facing the same issue-
'custom animations set for my fragments. Commenting out the call to set the custom animation, fixed the issue.'

Do you find any solution for this? How to use animations without crash?

**Comment by codewrangler1** [comment]
@jaideepreddy...I don't know why it's happening, just know the workaround. If I figure it out, I will be sure to post the answer here...

**Comment by jaideepreddy** [comment]
Hi @codewrangler1, 
My issue got resolved by replacing getFragmentManager with getActivity().getSupportFragmentManager()

**Comment by codewrangler1** [comment]
@jaideepreddy, I am using 'getSupportFragmentMananger()' and still have the issue. So, the issue seems more elusive...

**Comment by PrasadCaioty** [comment]
I am getting same issue when I overlay TouchableHighlight button on top of react-native-maps. I am trying create button to toggle-switch between hybrid to satellite view.

- Prasad

**Comment by spysoos** [comment]
same issue, by build tool 27.0.2

**Comment by tehcpu** [comment]
So, eventually, the situation seems has cleared up a bit.
In agreement with the @codewrangler1's comment, I think it's really animation issue. After a rather long time in debugging, I managed to start to systematically reproduce the crash. In my case, the application always crashed when I "quickly" (before the previous transition animation ends) was switching between tabs (`mNavController.switchTab()`) using my BottomBar's buttons. Then, I just disabled clicks on the `BottomBar` buttons when animation happens (until its fully completed), and that did the trick for me :)   So, if you also use an animation for fragment transitions, you may try to use something like this:

```
// init vars
private boolean transactionLocked = false; //
private int animationLength = 310; // fragment transition animation's duration + ~10ms

...

// modify onTabSelected method of your Bottom Bar
bottomBar.setOnTabSelectListener(new OnTabSelectListener() {
    @Override
    public void onTabSelected(@IdRes int tabId) {
        if (!transactionLocked) {
            transactionLocked = true;
            triggerBar(false);
            final Handler handler = new Handler();
            handler.postDelayed(new Runnable() {
                @Override
                public void run() {
                    transactionLocked = false;
                    triggerBar(true);
                }
            }, animationLength);
            switch (tabId) {
                case R.id.bb_menu_feed:
                    mNavController.switchTab(INDEX_FEED);
                    break;
                case R.id.bb_menu_search:

                    ...

            }
        }
    }
}, initial);

...

// util methods
public void triggerBar(boolean enabled) {
    enableDisableView(bottomBar, enabled);
}

public void enableDisableView(View view, boolean enabled) {
    view.setEnabled(enabled);
    if ( view instanceof ViewGroup) {
        ViewGroup group = (ViewGroup)view;
        for ( int idx = 0 ; idx < group.getChildCount() ; idx++ ) {
            enableDisableView(group.getChildAt(idx), enabled);
        }
    }
}
```

**P.S.:** This isn't brilliant solution and very unoptimized, but its better than nothing, I think :). Also, I hope that this will be useful to someone or, perhaps, give food for thought about the true cause of this bug.

**Comment by yunussandikci** [comment]
Im facing with same issue. I just know that it is happening when trying to pop fragment while enter animation playing. But It doesn't happen in sample app. I changed every library to same one with sample app but doesn't resolve problem. @ncapdevi do you know why does it happen?

**Comment by ncapdevi** [comment]
I don't believe this is an issue specifically related to FragNav as is evident by the actual stacktrace provided in this issue (although of course, it's entirely possible that I'm wrong). As has been mentioned, it appears to be related to animations, and for that, FragNav isn't doing anything specific or different outside of the standard Android library. Until someone can trace down where it is that FragNav is doing something specific to cause this issue,  I'd suggest searching stackoverflow for this general issue.

[Here's one that may be of help to some of you]( https://stackoverflow.com/questions/10007094/java-lang-illegalstateexception-the-specified-child-already-has-a-parent/24819855) . And [Here's a longer list](https://stackoverflow.com/search?q=java.lang.IllegalStateException%3A+The+specified+child+already+has+a+parent)

If you find a solution, please report back to help others

**Comment by yunussandikci** [comment]
I removed fragnav and handled fragment navigations with usual way by fragment manager, same things error still happen.

**Comment by ncapdevi** [comment]
@yunussandikci Thanks for the feedback. That confirms that it is not an issue with FragNav and thus is either one of two things:
1.) An issue with the core Android libraries 
2.) an issue with the way that you are performing the transactions.

My guess is Stackoverflow is going to be the best bet to finding a solution to your particular situation.

**Comment by malwinder-s** [comment]
I fixed it by replacing:

`return inflater.inflate(R.layout.fragment_layout, container); 
`
with 
`return inflater.inflate(R.layout.fragment_layout, container, false);`

In my Fragment class.

**Comment by mohammadbahadori99** [comment]
> I fixed it by replacing:
> 
> `return inflater.inflate(R.layout.fragment_layout, container); `
> with
> `return inflater.inflate(R.layout.fragment_layout, container, false);`
> 
> In my Fragment class.

thank you man.you saved my life :)))

**Comment by vladbakalo** [comment]
@codewrangler1  I had the same issue because of animation as you and this code in `onDestroyView` method in Fragment fixed the crash

```
override fun onDestroyView() {
    if (rootView.parent != null){
      (rootView.parent as ViewGroup).endViewTransition(rootView)
    }
    super.onDestroyView()
}
```

**Comment by codewrangler1** [comment]
I don’t remember what this was for, specifically, but the onDestroyView() code listed here is subject to a crash, due to dereferencing ‘rootView’ without checking for null first.
