### ISSUE TITLE
pop fragment with transitionOption not working

### ISSUE THREAD

**Issue by rayhanuddin55** [ncapdevi/FragNav#83]
pop fragment with transitionOption worked fine in version 2.0.1. But in the current version(2.0.2) push work with transition option but pop not.

**Comment by sbfss** [comment]
Any update?

**Comment by ncapdevi** [comment]
Apologies. I haven't actually had a chance to look into this yet. Will try to do so in the coming days.

**Comment by porkyhead** [comment]
I also having trouble getting the correct behavior when using tranistionOption. I am not able to get the return transition working with a shared element. Any suggestions or progress on this issue?

**Comment by asshyy-ktz** [comment]
its not a bug, it seems the interface containing pushFragment() & popFragment() having only pushFragment() method.
only update the interface named "FragmentNavigation" in BaseFragement class by declaring function named " void popFragment(); "
then just implement popFragment() method in the class in which you implement this interface.

after updating sample code it look like:

public interface FragmentNavigation {
        void pushFragment(Fragment fragment);
        void popFragment();
    }

    @Override
    public void popFragment() {
        if (mNavController != null) {
            mNavController.popFragment();
        }
    }

**Comment by ncapdevi** [comment]
@ismaielsharif Your comment isn't relevant for the transactionOptions which is the original issue, and your provided solution is only necessary if the fragments themselves need to initiate a pop, which is rarely the case as it's often handled by the Activity and back navigation as can be seen in `BottomTabsActivity.kt`


```
   override fun onBackPressed() {
        if (fragNavController?.popFragment()?.not() == true) {
            super.onBackPressed()
        }
    }
```

This issue is for discussion a problem with transitionOptions, not general pop navigation

**Comment by ncapdevi** [comment]
I believe this issue has been corrected, but if it hasn't please comment and I'll reopen

**Comment by sebastianmarschall** [comment]
the issue still persists in 2.4.0
please reopen @ncapdevi

**Comment by diogojg** [comment]
Yes, I have the same issue. Any workaround?

**Comment by diogojg** [comment]
@rayhanuddin55 I can't even get it to work on back press on the version you mentioned '2.0.1'.
The shared elements transition works well on pushing a new fragment, but when I do popFragment() only the typical Fade animation is performed, and no shared elements in the transition.

**Comment by porkyhead** [comment]
Same issue here as described by @diogojg 

@rayhanuddin55 or @ncapdevi Will you reopen this issue?

**Comment by chnouman** [comment]
same issue please reopen it.

**Comment by fr-hyun** [comment]
Is there someone or project to fix this issue? 
I want to help to solve this

**Comment by ugurcany** [comment]
+1

**Comment by ncapdevi** [comment]
Should be fixed in 3.1.0 #187

**Comment by javad-vovin** [comment]
I still have this issue, after updating to 3.1.0

**Comment by porkyhead** [comment]
Still cannot get it to work with 3.1.0. 

@ncapdevi Do you have a sample showing how it should be done in 3.1.0?

**Comment by mecoFarid** [comment]
Using the latest `3.2.0` version popAnimation is still not working.

**Comment by khunzohn** [comment]
Yet not working for 3.3.0
